export enum SUCCESS_MSGS {
  DB_CONNECTED = 'Base de datos conectada 🔥🔥🔥',
  OTP_SENT = 'El código para usar la app fue enviado correctamente',
  VERIFY_OTP_SUCCESS = 'Código verificado correctamente',
  BARBER_CREATED = 'Barbero creado correctamente',
  GET_BARBERS_SUCCESS = 'Barberos enviados correctamente',
  DELETED_BARBER_SUCCESS = 'Barbero eliminado correctamente',
  GET_BARBER_SUCCESS = 'Barbero obtenido correctamente',
  MODIFIED_BARBER_SUCCESS = 'Barbero modificado correctamente',
  SERVICE_CREATED = 'Servicio creado correctamente',
  DELETED_SERVICE_SUCCES = 'Servicio borrado correctamente',
  GET_SERVICE_SUCCES = 'Servicio obtenido correctamente',
  MODIFIED_SERVICE_SUCCESS = 'Servicio modificado correctamente',
  GET_SERVICES_SUCCESS = 'Servicios obtenidos correctamente',
  GET_BARBERS_WITH_THEIR_SERVICES_SUCCESS = 'Barberos con sus servicios obtenidos correctamente',
  MODIFIED_CLIENT_SUCCESS = 'Cliente modificado correctamente',
  DELETED_CLIENT_SUCCESS = 'Cliente borrado correctamente',
  GET_CLIENTS_SUCCESS = 'Clientes enviados correctamente',
  CLIENT_CREATED = 'Cliente creado correctamente',
  DELETED_APPOINTMENT_SUCCESS = 'Cita borrada correctamente',
  MODIFIED_APPOINTMENT_SUCCESS = 'Cita modificada correctamente',
  CREATED_APPOINTMENT_SUCCESS = 'Cita creada correctamente',
  APPOINTMENT_COMPLETED = 'Cita finalizada.',
  GET_APPOINTMENTS_SUCCESS = 'Citas obtenidas correctamente',
  APPOINTMENT_CANCELED = 'Cita cancelada correctamente',
  APPOINTMENT_CREATION_EMAIL_SUBJECT = 'Se agendó su nuevo turno en BurberBuddy',
  APPOINTMENT_CANCELATION_EMAIL_SUBJECT = 'Tu turno en BurberBuddy fue cancelado'
}
